### ISSUE TITLE
Dead link on hompage

### ISSUE THREAD

**Issue by DaVarga** [ryanbenson/Harvest#12]
link to documentation is dead - http://www.ryanbensonmedia.com/documentation

**Comment by ryanbenson** [comment]
Oops, my bad. Thanks for catching that! I'm on vacation at the moment but
I'll try to fix it soon, maybe later this week.

**Comment by YanMagale** [comment]
@DaVarga this documentation stay this link http://www.ryanbensonmedia.com/harvest/documentation

**Comment by DaVarga** [comment]
Yes, i found it myself. But thanks.

**Comment by ryanbenson** [comment]
Ah! My sincere apologies, I completely forgot about this. I fixed the link on the harvest home page. Sorry about that! But I'm glad you were able to find it, and thanks for jumping in @YanMagale to help with this!
