### ISSUE TITLE
out-date Packages npm 

### ISSUE THREAD

**Issue by selique** [ryanbenson/Harvest#15]
i revice this Message when try install packages ->npm WARN package.json FrontFriend@0.0.1 No repository field.    

i try change the package.json for bower.json and revice the messages -> bower browser-sync#^2.9.11   ENOTFOUND Package browser-sync not found   and ->bower gulp-concat#^2.6.0     ENOTFOUND Package gulp-concat not found 

well, i tried doing the manual installation, but the result is equal.

**Comment by ryanbenson** [comment]
You can safely ignore the WARN messages about the repository field and the license field as they're really just minor notices. But if you want them to go away, you'll need to fill in those elements in your package.json as those would be unique to your project.

As for the bower issue, I'm not sure I understand. What are you trying to do?

**Comment by selique** [comment]
I'm doing something quite unusual if you take into account, but do not believe that is the problem, open a machine in codio.com site with a standard php stack, inside I uploaded the github repository of files and start via terminal codio the installation command. I understand your answer but did not understand why inside the terminal codio the command '$ gulp' not start. if you can take the test as explained above would be interesting, because the codio up a virtual Linux environment.

**Comment by ryanbenson** [comment]
Interesting! I made an account, but I can't use the terminal with a free account, so I can't test it in that SaaS environment. Have you tried running it locally? And when you run `gulp`, are you typing in the $?

**Comment by selique** [comment]
its so strangely because all account have access to terminal on codio.
![ssa](https://cloud.githubusercontent.com/assets/1678894/10728495/8643132e-7bc9-11e5-9f41-c81fdfd861da.png)

**Comment by ryanbenson** [comment]
Are you paying for the service? I signed up for a free account and it won't let me access to the terminal.

![screen shot 2015-10-26 at 12 45 47 pm](https://cloud.githubusercontent.com/assets/588599/10737346/97daa6d6-7bdf-11e5-8b72-a06d93beaed2.png)

**Comment by selique** [comment]
oh, sorry i have accont so old i dont remenber this ... but i belive youre can drop this issue, i resolve de npm with change path of repository NPM

**Comment by ryanbenson** [comment]
I'm glad you were able to get it working :)

**Comment by selique** [comment]
i recommend add the params for a better and more complete installation
$ npm install -g gulp

**Comment by ryanbenson** [comment]
Thanks for the tip. I added a note about needing Gulp installed, and the CLI task to install it on the main README: https://github.com/ryanbenson/Harvest/commit/eb2c1ed81e312aa2559c34bc9a83e67afed3e024
