### ISSUE TITLE
unused devDependency, gulp-connect

### ISSUE THREAD

**Issue by dnmd** [ryanbenson/Harvest#16]
it's almost not worth mentioning :) but gulp-connect is no longer a devDependency, [package.json, line 11](https://github.com/ryanbenson/Harvest/blob/master/package.json#L11)

furthermore, excellent repo!!

**Comment by ryanbenson** [comment]
Thanks for catching that! I was using it a while ago, but I think it got deprecated when I switched to browser-sync. I removed it from the package.json :) https://github.com/ryanbenson/Harvest/commit/eb2c1ed81e312aa2559c34bc9a83e67afed3e024

And I'm glad you like the repo! Enjoy!
