### ISSUE TITLE
gulp crashes after scss error

### ISSUE THREAD

**Issue by lowenf** [ryanbenson/Harvest#17]
Hey! Thanks so much for this boilerplate, just started using it recently and love it. 

Except when having an scss error ;) (in my case, forgetting a semicolon)

When I fix the error, gulp does compile the scss files anymore. I have to restart gulp in order for it to work again. It still does other tasks though, just the scss one crashes I guess.

**Comment by lowenf** [comment]
alright I fixed the error. Made a fork of your repo, comitted and pushed the fix, but not sure what to do next to add the bug fix.. (git noob here).

**Comment by jkrot** [comment]
U submit a pull request to the original repo.

**Comment by ryanbenson** [comment]
Wow that was fast haha. I planned on looking at it today, but that's awesome if you have the fix :) Yea, just submit a pull request and I'll check it out and merge it in. I'm glad you are enjoying the boilerplate!

**Comment by lowenf** [comment]
cool! learned something new today :) check it out

**Comment by ryanbenson** [comment]
I merged in your PR, thanks for your help! That drove me nuts too.
