### ISSUE TITLE
Gracefull-fs module error

### ISSUE THREAD

**Issue by jm-kumaresh** [ryanbenson/Harvest#22]
After running the command `gulp` it throws me the error attached in the screenshot. Could you help with this..?

![harvest](https://cloud.githubusercontent.com/assets/2070512/16261056/ae63ec4a-3887-11e6-8874-1ba1337f48b3.jpg)

**Comment by ryanbenson** [comment]
Hey @jm-kumaresh, thanks for the error report. I tested the current version just now and it worked okay. What version of Node are you running? (I'm on 4.4.3 and 6.2). I see that you're on Windows too, which may have something to do with it.

In my test, I noticed some packages were out of date so I'll fix those and I saw one got renamed which I'll fix too. But let me know what version of Node you're running so I can try to test it on a VM or something.

Thanks!

**Comment by ryanbenson** [comment]
Update:
I got a VM with Windows 10 and 4.4.x running. I cloned Harvest, installed the dependencies and ran `gulp` and it worked as expected. So, that's weird. Maybe try running `npm install` again to make sure it caught all of the dependencies. From the error, it might be missing some. If that doesn't help, let me know what Windows version you're running and Node version and I'll try to replicate it on my end.

Thanks!

**Comment by jkrot** [comment]
This might be just a node or version issue version 6 has issues with
graceful-fs earlier versions.  I know that gulp currently has issues with
it till version 4 and a bunch of other libraries have dependency issues
with it as well.  My suggestion is downgrade to the latest version of node
on 5 and that will fix your issues after you reinstall node again.  I
currently am using NVM for mac to bounce back and forth between versions
because of this issue with some of my other libraries.

James

**Comment by jm-kumaresh** [comment]
Hi @ryanbenson . Thanks for your reply. I have updated the node js to the latest version and its working fine now. However I still got the `graceful-fs` module message (Refer the screenshot). Is that fine o ignore that message..?

![harvest](https://cloud.githubusercontent.com/assets/2070512/16293189/6bf88be6-3935-11e6-8cbe-a5adbaff79ea.jpg)

Also I would like to know whether harvest has the feature to include html sections like **header or footer** using the package like **processhtml**. 

Kumaresh

**Comment by ryanbenson** [comment]
I'm happy to hear that it is working! And yes, it is safe to ignore the graceful-fs warning. From all my tests on different Node versions and seeing that error with Harvest, or other gulp workflows, it hasn't caused any problems for me. As @jkrot said, hopefully in newer versions of `gulp` the warning/notice will go away.

As for header, footer, and partials/templates, it has been on my list of things to implement along with other features. I've been setting up Handlebars myself, so I've considered making it a part of the core package along with some pre-setup partials like header, footer, navigation, etc. I'll try to work on getting something setup as part of the core package soon :)
