### ISSUE TITLE
Is there an Harvest way to control JS concat order to solve dependency issues?

### ISSUE THREAD

**Issue by quakenul** [ryanbenson/Harvest#5]
Something in app/scripts/src/main.js might try to utilize /app/scripts/src/_includes/jquery, which will fail due to wrong concat order.

Unless there is an Harvest way to do this, that I am missing here I would suggest this quick fix to put everything in /_includes before anything else, like so: https://github.com/quakenul/Harvest/blob/master/gulpfile.js

**Comment by ryanbenson** [comment]
I've had that same issue and I have struggled to find a way around it except using something like Browserify, but I think that's a bit outside of the scope of what Harvest is supposed to accomplish. I love your idea of pulling in _includes first before pulling in the other files. You can do a pull request and I'll merge it in. If not, I can make the quick update myself. What do you think?

Thanks for catching this and finding a good solution!

**Comment by quakenul** [comment]
Sure thing. Thanks for all your work on harvest :)
